'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm');
const {sha256,parseArchive,repack}=require('./lib/asar.cjs');
const {extractWebBundle}=require('./lib/zip.cjs');
const {nativePatches}=require('./lib/native-patches.cjs');
function compileMain(src,spec,dict){if(sha256(src)!==spec.mainSha256)throw Error('Front-end version hash mismatch');let end=0;const out=[];for(const edit of spec.edits){if(edit.start<end||src.slice(edit.start,edit.end)!==edit.expected)throw Error('Patch location mismatch at '+edit.start);let replacement;if(edit.kind==='expression')replacement=edit.replacement;else{if(!Object.hasOwn(dict,edit.key)||typeof dict[edit.key]!=='string')throw Error('Missing translation: '+edit.key);const zh=dict[edit.key];if(edit.kind==='string')replacement=JSON.stringify(zh);else if(edit.kind==='template'){const expected=edit.expressions.map((_,i)=>String(i));const actual=[...zh.matchAll(/\{(\d+)\}/g)].map(x=>x[1]);if(JSON.stringify(actual)!==JSON.stringify(expected))throw Error('Template placeholders changed: '+edit.key);let last=0,parts=['`'];for(const m of zh.matchAll(/\{(\d+)\}/g)){parts.push(escapeTemplate(zh.slice(last,m.index)),'${',edit.expressions[Number(m[1])],'}');last=m.index+m[0].length;}parts.push(escapeTemplate(zh.slice(last)),'`');replacement=parts.join('');}else throw Error('Unknown patch kind');}out.push(src.slice(end,edit.start),replacement);end=edit.end;}out.push(src.slice(end));let result=out.join('');for(const p of spec.displayPatches||[]){if(result.split(p.search).length!==2)throw Error('Display patch anchor mismatch');result=result.replace(p.search,p.replacement);}if(spec.runtimeDisplay)result='const __agZhMap='+JSON.stringify(dict)+';function __agZhUI(v){return typeof v==="string"&&Object.hasOwn(__agZhMap,v)?__agZhMap[v]:v}\n'+result;new vm.Script(result,{filename:'localized-main.js'});return result;}
function escapeTemplate(s){return s.replaceAll('\\','\\\\').replaceAll('`','\\`').replaceAll('${','\\${');}
function build(options={}){const root=__dirname,appPath=path.resolve(options.appPath||path.join(process.env.LOCALAPPDATA||'','Programs','antigravity'));const resources=path.join(appPath,'resources');const availableSpecs=['2.13.0.json','2.12.2.json'].map(f=>{const p=path.join(root,'patches',f);return fs.existsSync(p)?JSON.parse(fs.readFileSync(p,'utf8')):null}).filter(Boolean);const dict=JSON.parse(fs.readFileSync(path.join(root,'translations.zh-CN.json'),'utf8'));const candidates=[path.join(resources,'app.asar'),path.join(resources,'app.asar.original_backup'),path.join(resources,'zh-localization','.local-build','payload','app.english.asar'),path.join(resources,'zh-localization','payload','app.english.asar')];let original,spec;for(const name of candidates){if(fs.existsSync(name)){const b=fs.readFileSync(name);const hash=sha256(b);spec=availableSpecs.find(s=>s.asarSha256===hash);if(spec){original=b;break;}}}if(!original||!spec)throw Error('Matching original app.asar was not found. Supported versions: '+availableSpecs.map(s=>s.version).join(', ')+'.');
const native=parseArchive(original);const pkg=JSON.parse(native.get('package.json').toString());if(pkg.version!==spec.version||pkg.name!=='antigravity')throw Error('Unsupported application version: '+pkg.version);
const dest=path.resolve(options.output||path.join(root,'.local-build'));if(dest===appPath||dest===resources)throw Error('Build output cannot be the live installation');fs.mkdirSync(path.join(dest,'payload'),{recursive:true});const web=path.join(dest,'payload','web_bundle');if(fs.existsSync(web)&&fs.readdirSync(web).length)throw Error('Build output already contains a web bundle. Choose a new empty output directory.');const assets=extractWebBundle(path.join(resources,'bin','language_server.exe'),web);const main=fs.readFileSync(path.join(web,'main.js'),'utf8');const localized=compileMain(main,spec,dict);fs.writeFileSync(path.join(web,'main.js'),localized);
let html=fs.readFileSync(path.join(web,'index.html'),'utf8');html=html.replace(/<html lang="[^"]*">/,'<html lang="zh-CN">');fs.writeFileSync(path.join(web,'index.html'),html);fs.writeFileSync(path.join(dest,'payload','app.english.asar'),original);const changed=nativePatches(native);const patched=repack(original,changed);const verify=parseArchive(patched);for(const[name,content]of Object.entries(changed)){if(verify.get(name).toString()!==content)throw Error('ASAR round-trip failed');}fs.writeFileSync(path.join(dest,'payload','app.chinese.asar'),patched);
const files={};function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const full=path.join(dir,e.name);if(e.isDirectory())walk(full);else files[path.relative(dest,full).replaceAll('\\','/')]=sha256(fs.readFileSync(full));}}walk(path.join(dest,'payload'));const manifest={version:spec.version,patchVersion:'1.2.0',generated:new Date().toISOString(),dictionaryEntries:Object.keys(dict).length,translationCount:spec.edits.length,originalAsarSha256:spec.asarSha256,acceptedInstalledAsarSha256:[spec.asarSha256,...(spec.legacyAsarSha256||[]),sha256(patched)],nativeChangedFiles:Object.keys(changed),files};fs.writeFileSync(path.join(dest,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');console.log(JSON.stringify({build:dest,assets,translations:spec.edits.length,dictionary:Object.keys(dict).length,nativeFiles:Object.keys(changed).length,syntax:'passed',archive:'round-trip passed'}));return manifest;}
module.exports={build,compileMain};
if(require.main===module){try{const args=process.argv.slice(2);const value=k=>{const i=args.indexOf(k);return i>=0?args[i+1]:undefined};build({appPath:value('--app-path'),output:value('--output')});}catch(e){console.error('Build failed: '+e.message);process.exitCode=1;}}
